version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/billsdb
      REDIS_URL: redis://redis:6379/0
      # other env vars from settings
    depends_on:
      - db
      - redis

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billsdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/billsdb
      REDIS_URL: redis://redis:6379/0
      # other env vars
    depends_on:
      - db
      - redis
